language: node_js
node_js: stable

# Use macOS 10.12: https://docs.travis-ci.com/user/languages/objective-c/
os:
  - osx
  - linux
osx_image: xcode9.1
dist: trusty

install:
  - |
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      curl -LO https://github.com/neovim/neovim/releases/download/nightly/nvim-macos.tar.gz
      tar xzf nvim-macos.tar.gz
      export PATH="${PATH}:node_modules/.bin:$(pwd)/nvim-osx64/bin"
    else
      curl -LO https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.tar.gz
      tar xzf nvim-linux64.tar.gz
      export PATH="${PATH}:node_modules/.bin:$(pwd)/nvim-linux64/bin"
    fi
  - echo $PATH
  - nvim --version
  - npm install -g yarn
  - yarn global add codecov

script:
  - export NVIM_NODE_LOG_LEVEL=debug
  - yarn
  - yarn link
  - yarn run prep-integration-test
  - yarn test -- --coverage

after_success:
  - codecov

cache:
  directories:
    - $HOME/.cache/yarn

notifications:
  email:
    on_success: never # for now
    on_failure: never # for now
